
services:
  postgres:
    image: postgres:16
    container_name: postgres_test
    command:
        - "postgres"
        - "-c"
        - "max_connections=50"
        - "-c"
        - "shared_buffers=1GB"
        - "-c"
        - "effective_cache_size=4GB"
        - "-c"
        - "work_mem=16MB"
        - "-c"
        - "maintenance_work_mem=512MB"
        - "-c"
        - "random_page_cost=1.1"
        - "-c"
        - "temp_file_limit=10GB"
        - "-c"
        - "log_min_duration_statement=200ms"
        - "-c"
        - "idle_in_transaction_session_timeout=10s"
        - "-c"
        - "lock_timeout=1s"
        - "-c"
        - "statement_timeout=60s"
        - "-c"
        - "shared_preload_libraries=pg_stat_statements"
        - "-c"
        - "pg_stat_statements.max=10000"
        - "-c"
        - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "gsd7_923jeff3"
      PGDATA: "/var/lib/postgresql/data/test_data"
    ports:
      - "5435:5432"
    volumes:
      - postgres_test_data:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres_test


  pgadmin:
    container_name: pgadmin_test
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "timur.zverev@abbott.com"
      PGADMIN_DEFAULT_PASSWORD: "dji38sd3#kfD"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_test_data:/var/lib/pgadmin
    ports:
      - "5055:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres_test


volumes:
  postgres_test_data:
  pgadmin_test_data:

networks:
  postgres_test:
    driver: bridge


# create user test_user with password 'abbott123';
# grant all privileges on schema public to test_user;
# grant insert, select, update, delete on table persons to test_user;