

FROM ubuntu:22.04
# FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    openssh-server sudo supervisor iproute2 curl wget net-tools iputils-ping \
    lsb-release software-properties-common gnupg2 rsyslog \
    && mkdir /var/run/sshd \
    && echo 'root:password' | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && ssh-keygen -A

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]


