DROP TABLE IF EXISTS product_types CASCADE;
CREATE TABLE product_types(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_name VARCHAR(100)
);

DROP TABLE IF EXISTS customers CASCADE;
CREATE TABLE customers(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    email VARCHAR(30)
);

DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    type_id INT REFERENCES product_types(id),
    price INT
);

DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE,
    customer_id INT REFERENCES customers(id)
);

DROP TABLE IF EXISTS sales;
CREATE TABLE sales(
    product_id INT REFERENCES products(id),
    order_id INT REFERENCES orders(id),
    quantity INT,
    PRIMARY KEY(product_id, order_id)
);